name: ARCHE-Metadata-Ingest

on:
  workflow_dispatch

jobs:
  ingest_md:
    name: Ingest Metadata into ARCHE
    runs-on: ubuntu-latest
    env:
      ARCHE_USER: pandorfer
      ARCHE_PASSWORD: ${{secrets.ARCHE_PASSWORD}}
      ARCHE: https://arche.acdh.oeaw.ac.at/api
      TOPCOLID: https://id.acdh.oeaw.ac.at/pez-briefe
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: install python things
      run: pip install -r requirements.txt
    - name: Fetch the data
      run: ./fetch_data.sh
    - uses: actions/upload-artifact@v4
      with:
        name: arche-ttl
        path: to_ingest/arche.ttl
    - name: run metadata import
      run: ./arche/arche__ingest_md.sh
    
    
